algo: ppo
gail_experts_dir: './gail_experts'
log_interval: 1
env_name: 'PongNoFrameskip-v4'
save_dir: './trained_models/'
save_interval: 10000
eval_interval: 10
eval_eps: 0.2
num_env_steps: 3.0e+6
no_cuda: False
offset: 0
use_wandb: true
name: ""
cuda_deterministic: False

seed: 0

num_processes: 8
num_steps: 128
ppo_epoch: 4
num_mini_batch: 4

use_linear_lr_decay: true
lr: 2.5e-4
eps: 1.0e-05
alpha: 0.99
gamma: 0.99
use_gae: True
gae_lambda: 0.95
entropy_coef: 0.01
value_loss_coef: 0.5
max_grad_norm: 0.5
clip_param: 0.1

use_proper_time_limits: False

model:
  name: CNNBase
  recurrent: False
  hidden_size: 512
  avg_pool_size: 2
  inplanes: 64
  num_blocks: 2
  use_bn: true
  use_init: False


gail: False
gail_batch_size: 128
gail_epoch: 5

